/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as EmailGeneratorRouteImport } from './routes/email-generator'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StoreRouteImport } from './routes/store'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailGeneratorRoute = EmailGeneratorRouteImport.update({
  id: '/email-generator',
  path: '/email-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/store': typeof StoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/store': typeof StoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/chat': typeof ChatRoute
  '/email-generator': typeof EmailGeneratorRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/store': typeof StoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/chat'
    | '/email-generator'
    | '/profile'
    | '/services'
    | '/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/chat'
    | '/email-generator'
    | '/profile'
    | '/services'
    | '/store'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/chat'
    | '/email-generator'
    | '/profile'
    | '/services'
    | '/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  ChatRoute: typeof ChatRoute
  EmailGeneratorRoute: typeof EmailGeneratorRoute
  ProfileRoute: typeof ProfileRoute
  ServicesRoute: typeof ServicesRoute
  StoreRoute: typeof StoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-generator': {
      id: '/email-generator'
      path: '/email-generator'
      fullPath: '/email-generator'
      preLoaderRoute: typeof EmailGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  ChatRoute: ChatRoute,
  EmailGeneratorRoute: EmailGeneratorRoute,
  ProfileRoute: ProfileRoute,
  ServicesRoute: ServicesRoute,
  StoreRoute: StoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
